### ISSUE TITLE
Profile must be enviroment variable

### ISSUE THREAD

**Issue by kongou-ae** [kongou-ae/yammer-rss-reader#1]
```
provider:
  name: aws
  runtime: nodejs4.3
  region: ap-northeast-1
  profile: lambda
```
